import Head from "next/head";
import Link from "next/link";
import { UserButton, useAuth, useUser } from "@clerk/nextjs";

import { api } from "~/utils/api";
import { useEffect, useState } from "react";
import { sign } from "crypto";
import { UserRole } from "~/utils/constants";
import { useRouter } from "next/router";
import { Spinner } from "@nextui-org/react";

export default function Home() {
	const [loading, setLoading] = useState(false);
	const { user, isLoaded, isSignedIn } = useUser();
	const { signOut } = useAuth();
	const router = useRouter();
	// const hello = api.post.hello.useQuery({ text: "from tRPC" });

	// biome-ignore lint/correctness/useExhaustiveDependencies: <explanation>
	useEffect(() => {
		setLoading(true);
		if (!isLoaded) {
			return;
		}

		if (isSignedIn) {
			if (Object.keys(user.unsafeMetadata).length > 0) {
				setTimeout(() => {
					router.push("/dashboard");
				}, 3000);
				if (user.unsafeMetadata.role !== UserRole.ADMIN) {
					setTimeout(() => {
						signOut();
					}, 3000);
				}
				return;
			}
			setTimeout(() => {
				signOut();
			}, 3000);
		}
	}, [isLoaded, isSignedIn, user]);

	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex min-h-screen flex-col items-center justify-center bg-primary">
				<Spinner />
			</main>
		</>
	);
}
